# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63309c728f5a1327b06dcd1af63445b912dee9e4e27353ff6df73ac4eb0002f2ea98214dc299af23041ad376fdeaa3b5ab1af815a5e40f1b8e38a07420bac476

test:
  secret_key_base: 5409c58efa305ff9d5213d4e9cd593001696d23430fd95bc8dc65ea6783ba4d04a8243a121c4fc79f3f7ff6d25eb729e0bfa1f56fa470ceffa9ec4d1e02ab497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
